// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUKcgdOk5e9XXjrvwfyuvYBpCn6v97Wo',
    appId: '1:627674550571:web:034d04865003568d64b56e',
    messagingSenderId: '627674550571',
    projectId: 'firestore-c9194',
    authDomain: 'firestore-c9194.firebaseapp.com',
    storageBucket: 'firestore-c9194.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnr6Tl2rIeLJsQSSuSvgh6Pj7MfNqGTOA',
    appId: '1:627674550571:android:f517bbe55ef7dbb164b56e',
    messagingSenderId: '627674550571',
    projectId: 'firestore-c9194',
    storageBucket: 'firestore-c9194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdBdaZOiSrMoOyqmmEZqVcNTLbib_pb0',
    appId: '1:627674550571:ios:6b6d7a2a68db9d5f64b56e',
    messagingSenderId: '627674550571',
    projectId: 'firestore-c9194',
    storageBucket: 'firestore-c9194.appspot.com',
    iosBundleId: 'com.example.fireestoreV3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtdBdaZOiSrMoOyqmmEZqVcNTLbib_pb0',
    appId: '1:627674550571:ios:a0febc2925a5291564b56e',
    messagingSenderId: '627674550571',
    projectId: 'firestore-c9194',
    storageBucket: 'firestore-c9194.appspot.com',
    iosBundleId: 'com.example.fireestoreV3App.RunnerTests',
  );
}
